#! /bin/sh

sxhkd &
# Applications
deepin-terminal &
google-chrome-stable &
atom &
dde-file-manager &
#
# Monitor configuration set.
xrandr --output HDMI1 --auto --primary
xrandr --output HDMI0 - auto --left-of HDMI1
# Workspaces defined.
bspc monitor HDMI-1 -d Primary Code Reading School X
bspc monitor HDMI-0 -d I { } III IV V

# Polybar
# $HOME/.config/polybar/launch.sh
# Disabled for now until a simpler configuration can be made.

# Works fantastic, but there is a slight glitch with lemonbar.
# For now, I'm going to disable this and personally specifiy a monitor.
#My monitor setup.
#for monitor in $(bspc query -M); do
#	bspc monitor $monitor -d A B C D E F
#done

#
bspc config border_width         2
bspc config window_gap           20

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Workspace 1
#
# Workspace 2
bspc rule -a dde-file-manager desktop=^2
#
bspc rule -a deepin-terminal desktop=^2 state=tiled
# Workspace 6
bspc rule -a Google-chrome desktop=^6
# Workspace 7
bspc rule -a Atom desktop=^7

bspc rule -a Screenkey manage=off

# Wallpaper using feh currently. #Daisy Ridley FTW. wallhaven-356407.png
# Terminal images: feh <image file> -B "<terminal bg color>" --scale-down
feh --bg-scale Pictures/wallpapers/wallpapers-updated/W/FZcN3zf.jpg

panel &
