#! /bin/sh

sxhkd &
deepin-terminal &
google-chrome-stable &

#bspc monitor -d I II III IV V VI VII VIII IX X

# Polybar
# $HOME/.config/polybar/launch.sh
# Disabled for now until a simpler configuration can be made. 
#My monitor setup.

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a google-chrome-stable desktop='^1'
bspc rule -a htop desktop=^1 state=floating
bspc rule -a deepin-terminal desktop=^1 state=floating
bspc rule -a Screenkey manage=off

# Wallpaper using feh currently. #Daisy Ridley FTW.
feh --bg-scale /home/shandian/Pictures/wallpapers/prefered/wallhaven-356407.png
